version: '3'
services:
  mqtt:
    image: fstehle/rpi-mosquitto
    restart: always

  web:
    build: ./docker/web
    restart: always
#    volumes:
#            - "./web:/"
  db:
    image: arm32v7/postgres
    restart: always
    environment:
       POSTGRES_PASSWORD: cqobqocbqo1233
    

